version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/dev.Dockerfile
    image: rsrp/trello-burndown-backend:latest-dev
    volumes:
      - /usr/src/app/packages/backend/node_modules
      - ./packages/backend:/usr/src/app/packages/backend

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
